[package]
name = "bee"
version = "0.1.0"
edition = "2021"
authors = ["flippette <me@flippo.cc>"]
license = "Unlicense"

[dev-dependencies]
criterion = "0.5"
proptest = "1.5"

[[bench]]
name = "fits"
harness = false
